"""mainsail completions — emit shell completion scripts.

Usage:
    mainsail completions bash
    mainsail completions zsh
    mainsail completions fish
    mainsail completions powershell

Pipe the output to your shell's completion location, e.g.:

    mainsail completions bash | sudo tee /etc/bash_completion.d/mainsail
    mainsail completions zsh > ~/.zsh/completions/_mainsail
    mainsail completions fish > ~/.config/fish/completions/mainsail.fish

Each completion script asks the running `mainsail` binary for its
applet list at completion time, so it stays accurate as new applets
ship — no need to regenerate after upgrading.
"""
from __future__ import annotations

import sys

from mainsail.common import err

NAME = "completions"
ALIASES: list[str] = []
HELP = "emit shell completion scripts (bash/zsh/fish/powershell)"


_BASH = r"""# bash completion for mainsail (and the mainsail-X aliases)
# Generated by `mainsail completions bash`.
_mainsail_complete() {
    local cur prev words cword
    _init_completion || return

    # If invoked as `mainsail`, the applet name is words[1].
    # If invoked as a hardlink/symlink (e.g. `ls`, `dir`, `cat`),
    # there's no applet word -- we still let the user complete files.
    local prog="$(basename -- "${words[0]}")"
    if [ "$prog" = "mainsail" ]; then
        if [ "$cword" -eq 1 ]; then
            local applets
            applets=$("${words[0]}" --list 2>/dev/null \
                | awk '{print $1}' \
                | grep -v '^$')
            applets+=" --list --help --version"
            COMPREPLY=( $(compgen -W "$applets" -- "$cur") )
            return
        fi
    fi
    # Default to filename completion for applet args.
    _filedir
}
complete -F _mainsail_complete mainsail
"""


_ZSH = r"""#compdef mainsail
# zsh completion for mainsail.
# Generated by `mainsail completions zsh`.

_mainsail() {
    local -a applets
    if (( CURRENT == 2 )); then
        local raw
        raw=$(mainsail --list 2>/dev/null)
        applets=( ${(f)"$(echo "$raw" | awk '{print $1}')"} )
        applets+=( --list --help --version )
        _describe -t applets 'applet' applets
        return
    fi
    _files
}

_mainsail "$@"
"""


_FISH = r"""# fish completion for mainsail.
# Generated by `mainsail completions fish`.

# First positional after `mainsail` -> applet name.
complete -c mainsail -n '__fish_is_first_token' -f \
    -a "(mainsail --list 2>/dev/null | string trim | string replace -r '\\s+.*$' '')" \
    -d 'applet'

complete -c mainsail -n '__fish_is_first_token' -l list -d 'list applets'
complete -c mainsail -n '__fish_is_first_token' -l help -d 'show help'
complete -c mainsail -n '__fish_is_first_token' -l version -d 'show version'

# Subsequent positions: file completion.
complete -c mainsail -n 'not __fish_is_first_token' -F
"""


_POWERSHELL = r"""# PowerShell completion for mainsail.
# Generated by `mainsail completions powershell`.
# Add to your $PROFILE, or pipe directly: . (mainsail completions powershell | Out-String)

Register-ArgumentCompleter -Native -CommandName mainsail -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements
    if ($tokens.Count -le 2) {
        $applets = & mainsail --list 2>$null |
            ForEach-Object { ($_ -split '\s+')[1] } |
            Where-Object { $_ }
        $applets += @('--list', '--help', '--version')
        $applets |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_, $_, 'ParameterValue', $_
                )
            }
    }
}
"""


_GENERATORS = {
    "bash": _BASH,
    "zsh": _ZSH,
    "fish": _FISH,
    "powershell": _POWERSHELL,
    "pwsh": _POWERSHELL,
}


def main(argv: list[str]) -> int:
    args = argv[1:]
    if not args or args[0] in {"-h", "--help"}:
        from mainsail.usage import USAGE
        sys.stdout.write(f"{NAME} - {HELP}\n\n{USAGE.get(NAME, '')}")
        return 0
    shell = args[0].lower()
    body = _GENERATORS.get(shell)
    if body is None:
        err(NAME, f"unknown shell: {shell}. choose: bash, zsh, fish, powershell")
        return 2
    # Write through the binary buffer so Windows doesn't translate \n -> \r\n
    # on us — bash and zsh choke on CRLF in some configurations.
    sys.stdout.buffer.write(body.encode("utf-8"))
    sys.stdout.flush()
    return 0
